project_name: substreams-sink-kv

release:
  draft: true
  github:
    owner: streamingfast
    name: substreams-sink-kv
  name_template: '{{.Tag}}'
  target_commitish: '{{ .Commit }}'
  extra_files:
    - glob: build/substreams-sink-kv-{{.Tag}}.spkg

builds:
  - id: darwin-amd64
    main: ./cmd/substreams-sink-kv
    binary: substreams-sink-kv
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin-arm64
    main: ./cmd/substreams-sink-kv
    binary: substreams-sink-kv
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux-amd64
    main: ./cmd/substreams-sink-kv
    binary: substreams-sink-kv
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: substreams-sink-kv
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
    name_template: >-
      substreams_sink_kv_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
    format: tar.gz
    files:
    - LICENSE
    - README.md

snapshot:
  name_template: '{{ .Tag }}-next'

checksum:
  name_template: checksums.txt

dist: dist

brews:
  - name: substreams-sink-kv
    ids:
    - substreams-sink-kv
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/substreams-sink-kv"
    description: "Substreams Sink KV"
    license: "Apache-2.0"
